import {
    Save,
    FolderOpen,
    FilePlus,
    Database,
    Image,
    Crosshair,
    Maximize,
    RotateCcw,
    Download,
    Settings,
    Undo,
    Redo,
    EllipsisVertical,
    Plus,
    Eye,
    EyeOff,
    Lock,
    LockOpen,
    Trash2,
    ListX,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ArrowDown,
    Focus,
    Locate,
    LocateFixed,
    Palette,
    Pencil,
    OctagonAlert,
    ChartScatter,
    ChartLine,
    ChartSpline,
    CopyPlus,
    StepForward,
    StepBack,
} from 'lucide-react-native';

export const Icons = {
    save: Save,
    open: FolderOpen,
    newProject: FilePlus,
    dataset: Database,
    image: Image,
    calibration: Crosshair,
    fit: Maximize,
    resetView: RotateCcw,
    export: Download,
    settings: Settings,
    undo: Undo,
    redo: Redo,
    edit: Pencil,
    menu: EllipsisVertical,
    add: Plus,
    visible: Eye,
    notVisible: EyeOff,
    locked: Lock,
    notLocked: LockOpen,
    delete: Trash2,
    clearAll: ListX,
    nudgeLeft: ArrowLeft,
    nudgeRight: ArrowRight,
    nudgeUp: ArrowUp,
    nudgeDown: ArrowDown,
    centreImage: LocateFixed,
    palette: Palette,
    edit: Pencil,
    alert: OctagonAlert,
    hideCurve: ChartScatter,
    showCurveLine: ChartLine,
    showCurveSpline: ChartSpline,
    duplicate: CopyPlus,
    next: StepForward,
    previous: StepBack,
};